services:
    api:
        platform: linux/amd64
        build:
          context: ./api/
          dockerfile: Dockerfile
        restart: 'always'
        depends_on:
            - postgis
            - media
            - store
        ports:
            - "5000:5000"
        environment:
            - CLOUDTAK_Mode=${CLOUDTAK_Mode}
            - CLOUDTAK_Config_media_url=${CLOUDTAK_Config_media_url}
            - SigningSecret=${SigningSecret}
            - MediaSecret=${MediaSecret}
            - ASSET_BUCKET=${ASSET_BUCKET}
            - AWS_S3_Endpoint=${AWS_S3_Endpoint}
            - AWS_S3_AccessKeyId=${AWS_S3_AccessKeyId}
            - AWS_S3_SecretAccessKey=${AWS_S3_SecretAccessKey}
            - POSTGRES=${POSTGRES}
            - API_URL=${API_URL}
            - PMTILES_URL=${PMTILES_URL}

    tiles:
        platform: linux/amd64
        build:
          context: ./tasks/pmtiles/
          dockerfile: Dockerfile.compose
        restart: 'always'
        ports:
            - "5002:5002"
        environment:
            - PMTILES_URL=${PMTILES_URL}
            - SigningSecret=${SigningSecret}
            - MediaSecret=${MediaSecret}
            - ASSET_BUCKET=${ASSET_BUCKET}
            - AWS_S3_Endpoint=${AWS_S3_Endpoint}
            - AWS_S3_AccessKeyId=${AWS_S3_AccessKeyId}
            - AWS_S3_SecretAccessKey=${AWS_S3_SecretAccessKey}

    events:
        platform: linux/amd64
        build:
          context: ./tasks/events/
          dockerfile: Dockerfile
        restart: 'always'
        depends_on:
            - api
            - store
        ports:
            - "5003:5003"
        environment:
            - CLOUDTAK_Mode=${CLOUDTAK_Mode}
            - API_URL=${API_URL}
            - SigningSecret=${SigningSecret}
            - ASSET_BUCKET=${ASSET_BUCKET}
            - AWS_S3_Endpoint=${AWS_S3_Endpoint}
            - AWS_S3_AccessKeyId=${AWS_S3_AccessKeyId}
            - AWS_S3_SecretAccessKey=${AWS_S3_SecretAccessKey}

    media:
        image: ghcr.io/dfpc-coe/media-infra:v6.0.0
        restart: 'always'
        environment:
            - API_URL=${API_URL}
            - SigningSecret=${SigningSecret}
            - MediaSecret=${MediaSecret}
        ports:
            - "${MEDIA_PORT_API:-9997}:9997"
            - "${MEDIA_PORT_RTSP:-8554}:8554"
            - "${MEDIA_PORT_RTMP:-1935}:1935"
            - "${MEDIA_PORT_HLS:-8888}:8888"
            - "${MEDIA_PORT_SRT:-8890}:8890"
        volumes:
            - .docker-media:/opt/mediamtx

    postgis:
        platform: linux/amd64
        image: postgis/postgis:17-3.4-alpine
        restart: 'always'
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=gis
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker

    store:
        platform: linux/amd64
        image: minio/minio:RELEASE.2024-08-17T01-24-54Z
        entrypoint: sh
        command: -c 'mkdir -p /data/cloudtak && /usr/bin/minio server /data --console-address ":9002"'
        restart: 'always'
        volumes:
            - .docker-store:/data
        ports:
            - 9000:9000
            - 9002:9002
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
            - MINIO_DEFAULT_BUCKETS=${ASSET_BUCKET}
