services:
    api:
        platform: linux/amd64
        build: ./api/
        restart: 'always'
        links:
            - postgis
            - store
        ports:
            - "5000:5000"
        environment:
            - SigningSecret=coe-wildland-fire
            - POSTGRES=postgres://docker:docker@postgis:5432/gis
            - API_URL=localhost:5001

    postgis:
        platform: linux/amd64
        image: postgis/postgis:17-3.4-alpine
        restart: 'always'
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=gis
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker

    store:
        platform: linux/amd64
        image: minio/minio:RELEASE.2024-08-17T01-24-54Z
        restart: 'always'
        ports:
            - 9000:9000
        command: server /data
