version: '3'

services:
    api:
        platform: linux/amd64
        build: ./api/
        restart: always
        links:
            - postgis
        ports:
            - "5000:5000"
        environment:
            - POSTGRES=postgres://docker:docker@postgis:5432/gis
            - TAK_USERNAME
            - TAK_PASSWORD

    task:
        platform: linux/amd64
        build: ./tasks/geojson/

    pmtiles:
        platform: linux/amd64
        build: ./tasks/pmtiles/

    stats:
        platform: linux/amd64
        build: ./tasks/stats/

    hooks:
        platform: linux/amd64
        build: ./tasks/hooks/

    postgis:
        platform: linux/amd64
        image: postgis/postgis:15-3.3-alpine
        restart: 'always'
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=gis
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
