name: NPM Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - id: changelog
        name: Generate CHANGELOG
        run: echo "body=$(./release ${{steps.tag.outputs.tag}})" >> "$GITHUB_OUTPUT"

      - name: Github Release
        uses: softprops/action-gh-release@v2
        body: ${{steps.changelog.outputs.body}}
