name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  data:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Docker Data Task Build
        run: docker buildx build ./tasks/data -t cloudtak-data

      - name: Docker Data Task Lint
        run: docker run cloudtak-data:latest npm run lint

      - name: Docker Data Task Test
        run: docker run cloudtak-data:latest npm test

  hooks:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Docker Hooks Task Build
        run: docker buildx build ./tasks/hooks -t cloudtak-hooks

      - name: Docker Hooks Task Lint
        run: docker run cloudtak-hooks:latest npm run lint

      - name: Docker Data Task Test
        run: docker run cloudtak-hooks:latest npm test

  pmtiles:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha || github.sha}}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install
        working-directory: ./tasks/pmtiles/
        run: npm install

      - name: Lint
        working-directory: ./tasks/pmtiles/
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Docker Compose Build
        run: docker compose up --build -d postgis

      - name: Docker API Build
        run: docker compose build api

      - name: Docker API Lint
        run: docker run cloudtak-api:latest sh -c "npm install --include=dev && npm run lint"

      - name: Docker API Test
        run: docker run --network cloudtak_default
          -e "POSTGRES=postgres://docker:docker@postgis:5432/gis"
          cloudtak-api:latest npm test

      - name: Docker Cleanup
        run: docker compose kill
